### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by 300-michael** [macs300/Agency-Portal-Home-Page-Feedback#4]
<img width="1140" alt="Screenshot 2019-06-20 at 12 01 02" src="https://user-images.githubusercontent.com/52032846/59845777-1462ca80-9356-11e9-8946-4a922da3f06c.png">

<img width="1068" alt="Screenshot 2019-06-20 at 12 36 49" src="https://user-images.githubusercontent.com/52032846/59846553-16c62400-9358-11e9-8852-90cdb0efc531.png">

**Pay attention to the resizing and distribution of content; Desktop and Mobile sizes.**

- make content fit 100% inside the **container**.
- max-width of the **container: 800px** and **auto left and right margins**.
- Edit line: `<h3>Take the first step to Agency Portal</h3>` 
to: `<h3>Get in touch</h3>`
- Add line below h3: `<p>Do you have more questions about Agency Portal? Please leave us a message and our team will contact you as soon as possible</p>`  
- Remove: `style="background-image: url(&quot;../img/img_bg_form.png&quot;);"` 
from: `<div class="form__card card form__card--background" style="background-image: url(&quot;../img/img_bg_form.png&quot;);">`
- Edit line: `<h4>Get the Agency Portal for free</h4> to <h4>Leave your details with us:</h4>`
- Remove line: `<p>Learn how to sell smarter and faster with Agency Portal.</p>`
- Edit placeholder text for telephone: `<input class="form__input js-field__phone" type="text" placeholder="(+44) 07700 900662" required="">` 
- Edit text: `<span class="checkbox-btn__label">...</span>`
to: `I want to receive updates from Agency Portal for product updates, services and events.`
- Edit text: `<p class="submission-para">...</p>`
to: `By clicking submit you agree to our <a>Terms of Service</a> and <a>Privacy Policy</a>`

**Comment by shancasperon** [comment]
This has been completed
