### ISSUE TITLE
Navbar Links colors do not change to indicate page.

### ISSUE THREAD

**Issue by 300-michael** [macs300/Agency-Portal-Home-Page-Feedback#5]
Changing page should change text colour on navigation bar to indicate the current page.

<img width="1071" alt="Screenshot 2019-06-20 at 13 53 17" src="https://user-images.githubusercontent.com/52032846/59850741-e9cb3e80-9362-11e9-994b-c25684e82fe1.png">
<img width="1068" alt="Screenshot 2019-06-20 at 13 53 11" src="https://user-images.githubusercontent.com/52032846/59850742-e9cb3e80-9362-11e9-9490-12c5c483049f.png">

<img width="838" alt="Screenshot 2019-06-20 at 13 58 46" src="https://user-images.githubusercontent.com/52032846/59851059-8d1c5380-9363-11e9-8737-2f828eb8151a.png">
<img width="695" alt="Screenshot 2019-06-20 at 13 58 51" src="https://user-images.githubusercontent.com/52032846/59851060-8db4ea00-9363-11e9-8103-5435804630a5.png">

**Comment by shancasperon** [comment]
This has been completed and will be moved to live today
